# Generated by Django 2.1.2 on 2018-10-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='location',
            new_name='preferred_loc',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.CharField(max_length=5),
        ),
    ]
