# Generated by Django 2.1.2 on 2018-10-26 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_auto_20181026_0501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='corrected_loc',
        ),
    ]
