# Generated by Django 2.1.2 on 2018-10-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_remove_candidate_corrected_loc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='analytics_exp',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
